description = "開発内容の解説ド-キュメントを生成します。生成結果はリダイレクトして docs/explain_dev/ 以下に保存。"

prompt = """
あなたはシニアソフトウェアエンジニアです。
与えられた開発内容について、他の技術スタックを持つエンジニアにも分かりやすく解説するドキュメントを作成してください。

# ドキュメントの目的と読者

- **目的**: 行われた開発作業の「なぜ」「何を」を明確に伝えること。
- **主な読者**: プロジェクトに参加しているが、今回の開発で使われた技術（例: Kotlin/KMP）に馴染みのないソフトウェアエンジニア（想定読者層: PHPエンジニア）。専門用語を避け、適宜アナロジーを用いて解説することが重要です。

# 生成プロセス

以下の手順でドキュメントを生成してください。

1.  **情報収集**: 関連するプルリクエストやコミットを特定し、変更内容を把握します。
2.  **内容執筆**: 以下の構造テンプレートに従って、構造化して執筆します。

# ドキュメントの構造テンプレート

```markdown
# プルリクエストURL
- [該当のプルリクエストのURL]

# [機能名] の実装解説

今回の開発は、[開発内容の概要] をしたものです。[対象読者]に分かりやすいように、具体的な内容を解説します。

## 背景：なぜこの開発を行ったのか？

[この機能が必要になった理由、解決しようとした課題などを記述します。]

## 具体的な開発内容

[コードレベルでの具体的な変更点を、複数のサブセクションに分けて説明します。]

### [変更点1]

[変更点1の詳細。]

### [変更点2]

[変更点2の詳細。]

## [対象読者向け] アナロジー/まとめ

今回の作業を [対象読者の技術スタック] (例: Laravel) での開発に例えるなら、[どのような実装に相当するかを記述します]。
```

# ドキュメントの保存先

以下のコマンドを実行して、開発内容の解説を `docs/explain_dev` ディレクトリに保存します。
`{pull_request_number}` `{YYYYMMDD}` の部分は実際の値に置き換えてください。

```bash
touch docs/explain_dev/{YYYYMMDD}_{pull_request_number}.md
```

"""
